### ISSUE TITLE
Tests Failing after neighbour update

### ISSUE THREAD

**Issue by SimonTreu** [maqnius/compscie-mc#27]
Since the last commit to neighbouring there are 4 failing tests. I didn't yet review it completely but it might be a rounding error do to this change:

 -        nr_cells = int(self.box_size/r + 1)
is changed to
 +        nr_cells = int(box_size / r)

i had the +1 to force a round up allways. 

To see the errors run pytest in the project directory

**Comment by maqnius** [comment]
There was a code snippet, where`nr_cells` was replaced by 1 if it is zero with `max(1, nr_cells)`. But this code snippet was inserted **after** a division is operated. I just changed the order of those commands, not checking if it makes sense in the big picture tho - but tests are running through now again (there were some more minor things to change due to changing attribute names).

But Thomas is making more basic changes to the neighbourlist at the moment, so I'm not going to dig deeper into the code atm.
